repos:
  - repo: local
    hooks:
      - id: hatch-lint
        name: Hatch Lint Check
        entry: hatch run lint:check
        language: system
        pass_filenames: false

exclude: ^mite_finagle/tests/foo_service/.*